[[main]]
identifier="timeline"
name="Timeline"
url="/year/"
weight=1

[[main]]
parent="timeline"
name="2026"
url="/year/2026/"
weight=10

[[main]]
parent="timeline"
name="2025"
url="/year/2025/"
weight=11

[[main]]
parent="timeline"
name="2024"
url="/year/2024/"
weight=12

[[main]]
identifier="concerts"
name="Concerts"
url="/categories/concerts/"
weight=2

[[main]]
identifier="murmurs"
name="Ramblings"
url="/categories/murmurs/"
weight=3
