[[main]]
identifier="timeline"
name="Timeline"
url="/categories/"
weight=1

[[main]]
parent="timeline"
name="2025"
url="/categories/2025/"
weight=10

[[main]]
parent="timeline"
name="2024"
url="/categories/2024/"
weight=11

[[main]]
identifier="murmurs"
name="Ramblings"
url="/categories/murmurs/"
weight=2
